config/routes.rb
Rails.application.routes.draw do
  root "galleries#index"

  resources :galleries, only: [:index, :new, :create, :show] do
    resources :paintings, only: [:index, :new, :create]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :paintings
  
  validates :name, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true, length: { is: 5 }

end

app/models/painting.rb
class Painting < ApplicationRecord
  belongs_to :gallery

  validates :title, presence: true
  validates :artists, presence: true
  validates :gallery, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController

  def index
    @galleries = Gallery.all
  end

  def new
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)

    if @gallery.save
      flash[:notice] = "Gallery added!"
      redirect_to gallery_path(@gallery)
    else
      flash[:notice] = @gallery.errors.full_messages
      render :new
    end
  end

  def show
    @gallery = Gallery.find(params[:id])
    @paintings = @gallery.paintings
  end

  private

  def gallery_params
    params.require(:gallery).permit(:name, :city, :state, :zip, :description)
  end

end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController

  def new
    @gallery = Gallery.find(params[:gallery_id])
    @painting = Painting.new
  end

  def create
    @gallery = Gallery.find(params[:gallery_id])
    @painting = Painting.new(painting_params)
    @painting.gallery = @gallery
    if @painting.save
      flash[:notice] = "Painting added!"
      redirect_to gallery_path(@gallery)
    else
      flash[:notice] = @painting.errors.full_messages
      render :new
    end
  end

  def painting_params
    params.require(:painting).permit(:title, :artists)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/galleries/index.html.erb
<h1> Great Gallery <h1>

  <ul>
    <% @galleries.each do |gallery| %>
    <li><%= gallery.name %></li>
      <%end%>
  </ul>

  <%= link_to "New Gallery", new_gallery_path %>

app/views/galleries/new.html.erb
<% if flash[:notice]%>
  <% flash.each do |key, msg| %>
    <%= msg %>
  <% end %>
<% end %>


<%= form_for (@gallery) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zip %>
  <%= f.text_field :zip %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>


 <% end %>

app/views/galleries/show.html.erb
<h1><%= @gallery.name%></h1>
<p>
  <%= @gallery.city%>
  <%= @gallery.state%>
  <%= @gallery.zip%>
  <%= @gallery.description%>
</p>

<h2> Featured paintings </h2>

<% @paintings.each do |painting| %>
  <p> Title: </p> <%= painting.title %>
  <p> Artist(s)</p> <%= painting.artists %>
<% end %>

<%= link_to 'Add Painting', new_gallery_painting_path(@gallery) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>gallery Reviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/paintings/new.html.erb
<% if flash[:notice]%>
  <% flash.each do |key, msg| %>
    <%= msg %>
  <% end %>
<% end %>


<%= form_for [@gallery, @painting] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :artist %>
  <%= f.text_field :artists %>

  <%= f.submit %>


 <% end %>